---
- name: Check k0s supported arch
  when: "ansible_architecture not in k0s_supported_archs"
  fail:
    msg: "K0s is not supported for architecture: {{ansible_architecture}}"

- name: Set k0s supported arch
  set_fact:
    k0sArch: '{{k0s_supported_archs[ansible_architecture]}}'
